Fix Webpack configurations
**CHANGES**

- Fix extension resolving sequence. Empty string (`''`) SHOULD ALWAYS be
  the last item in`resolve.extenstions`. This patch also fixes strange
  RunTime error on incremental builds:

> TypeError: undefined is not an object (evaluating 'fn.apply')

- Boost development build. _optimize.DedupePlugin_ was removed from
  plugins as it conflicts with CachePlugin:

> WARNING in CachePlugin - Cache cannot be used because of: DedupePlugin

As for production builds, DedupePlugin is enabled through CLI flag
`--optimize-dedupe`, so ALWAYS use `npm/yarn run build` to generate
production builds.